name: Testes com Pytest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Define os passos 
    steps: 
    - name: Checkout do código
      #  baixa seu código para o runner
      uses: actions/checkout@v4

    - name: Configurar Python
      # 'actions/setup-python' configura o ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Instalar dependências
      #instala o pytest
      run: pip install pytest

    - name: Rodar Testes
      #executa os testes usando o pytest
      run: pytest
