name: Testes com Pytest

# Este workflow é acionado em pushes e pull requests para a branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Define os passos 
    steps: 
    - name: Checkout do código
      # A action  baixa seu código para o runner
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' #usa aversão mais recente do Python 3

    - name: Instalar dependências
      # Instala o pytest
      run: pip install pytest

    - name: Rodar Testes
      # Executa os testes usando o pytest
      run: pytest
